import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import {
  users,
  profiles,
  subjects,
  topics,
  questions,
  tests,
  testQuestions,
} from "./schema";
import bcrypt from "bcryptjs";

const DATABASE_URL =
  process.env.DATABASE_URL ||
  "postgresql://postgres@localhost:5432/placement_os";

async function seed() {
  const pool = new pg.Pool({ connectionString: DATABASE_URL });
  const db = drizzle(pool);

  console.log("🌱 Seeding Placement OS database...\n");

  // ==========================================
  // 1. SUBJECTS
  // ==========================================
  console.log("📚 Creating subjects...");
  const subjectData = [
    { name: "Aptitude", code: "APT", category: "aptitude", displayOrder: 1 },
    {
      name: "Data Structures & Algorithms",
      code: "DSA",
      category: "cs",
      displayOrder: 2,
    },
    {
      name: "Database Management Systems",
      code: "DBMS",
      category: "cs",
      displayOrder: 3,
    },
    {
      name: "Operating Systems",
      code: "OS",
      category: "cs",
      displayOrder: 4,
    },
    {
      name: "Computer Networks",
      code: "CN",
      category: "cs",
      displayOrder: 5,
    },
    {
      name: "Object Oriented Programming",
      code: "OOP",
      category: "cs",
      displayOrder: 6,
    },
    { name: "SQL", code: "SQL", category: "cs", displayOrder: 7 },
  ];

  const insertedSubjects = await db
    .insert(subjects)
    .values(subjectData)
    .returning();
  const subjectMap: Record<string, string> = {};
  insertedSubjects.forEach((s) => {
    subjectMap[s.code] = s.id;
  });
  console.log(`  ✓ ${insertedSubjects.length} subjects created`);

  // ==========================================
  // 2. TOPICS
  // ==========================================
  console.log("📖 Creating topics...");
  const topicData: {
    subjectCode: string;
    name: string;
    displayOrder: number;
  }[] = [
    // Aptitude
    { subjectCode: "APT", name: "Quantitative Aptitude", displayOrder: 1 },
    { subjectCode: "APT", name: "Logical Reasoning", displayOrder: 2 },
    { subjectCode: "APT", name: "Verbal Ability", displayOrder: 3 },
    { subjectCode: "APT", name: "Number Systems", displayOrder: 4 },
    { subjectCode: "APT", name: "Percentages & Ratios", displayOrder: 5 },
    { subjectCode: "APT", name: "Time & Work", displayOrder: 6 },
    { subjectCode: "APT", name: "Probability", displayOrder: 7 },
    { subjectCode: "APT", name: "Permutations & Combinations", displayOrder: 8 },
    // DSA
    { subjectCode: "DSA", name: "Arrays", displayOrder: 1 },
    { subjectCode: "DSA", name: "Strings", displayOrder: 2 },
    { subjectCode: "DSA", name: "Linked Lists", displayOrder: 3 },
    { subjectCode: "DSA", name: "Stacks", displayOrder: 4 },
    { subjectCode: "DSA", name: "Queues", displayOrder: 5 },
    { subjectCode: "DSA", name: "Trees", displayOrder: 6 },
    { subjectCode: "DSA", name: "Graphs", displayOrder: 7 },
    { subjectCode: "DSA", name: "Sorting", displayOrder: 8 },
    { subjectCode: "DSA", name: "Searching", displayOrder: 9 },
    { subjectCode: "DSA", name: "Dynamic Programming", displayOrder: 10 },
    { subjectCode: "DSA", name: "Hashing", displayOrder: 11 },
    { subjectCode: "DSA", name: "Recursion", displayOrder: 12 },
    // DBMS
    { subjectCode: "DBMS", name: "ER Model", displayOrder: 1 },
    { subjectCode: "DBMS", name: "Keys", displayOrder: 2 },
    { subjectCode: "DBMS", name: "Normalization", displayOrder: 3 },
    { subjectCode: "DBMS", name: "Transactions", displayOrder: 4 },
    { subjectCode: "DBMS", name: "SQL Fundamentals", displayOrder: 5 },
    { subjectCode: "DBMS", name: "Indexing", displayOrder: 6 },
    { subjectCode: "DBMS", name: "Concurrency Control", displayOrder: 7 },
    { subjectCode: "DBMS", name: "Relational Algebra", displayOrder: 8 },
    // OS
    { subjectCode: "OS", name: "Processes", displayOrder: 1 },
    { subjectCode: "OS", name: "Threads", displayOrder: 2 },
    { subjectCode: "OS", name: "CPU Scheduling", displayOrder: 3 },
    { subjectCode: "OS", name: "Process Synchronization", displayOrder: 4 },
    { subjectCode: "OS", name: "Deadlocks", displayOrder: 5 },
    { subjectCode: "OS", name: "Memory Management", displayOrder: 6 },
    { subjectCode: "OS", name: "Virtual Memory", displayOrder: 7 },
    { subjectCode: "OS", name: "File Systems", displayOrder: 8 },
    // CN
    { subjectCode: "CN", name: "OSI Model", displayOrder: 1 },
    { subjectCode: "CN", name: "TCP/IP", displayOrder: 2 },
    { subjectCode: "CN", name: "HTTP & HTTPS", displayOrder: 3 },
    { subjectCode: "CN", name: "DNS", displayOrder: 4 },
    { subjectCode: "CN", name: "Subnetting", displayOrder: 5 },
    { subjectCode: "CN", name: "Routing", displayOrder: 6 },
    { subjectCode: "CN", name: "Transport Layer", displayOrder: 7 },
    { subjectCode: "CN", name: "Network Security", displayOrder: 8 },
    // OOP
    { subjectCode: "OOP", name: "Classes & Objects", displayOrder: 1 },
    { subjectCode: "OOP", name: "Inheritance", displayOrder: 2 },
    { subjectCode: "OOP", name: "Polymorphism", displayOrder: 3 },
    { subjectCode: "OOP", name: "Abstraction", displayOrder: 4 },
    { subjectCode: "OOP", name: "Encapsulation", displayOrder: 5 },
    { subjectCode: "OOP", name: "Design Patterns", displayOrder: 6 },
    { subjectCode: "OOP", name: "SOLID Principles", displayOrder: 7 },
    { subjectCode: "OOP", name: "Interfaces & Abstract Classes", displayOrder: 8 },
    // SQL
    { subjectCode: "SQL", name: "SELECT Queries", displayOrder: 1 },
    { subjectCode: "SQL", name: "Joins", displayOrder: 2 },
    { subjectCode: "SQL", name: "Aggregations", displayOrder: 3 },
    { subjectCode: "SQL", name: "Subqueries", displayOrder: 4 },
    { subjectCode: "SQL", name: "DDL & DML", displayOrder: 5 },
    { subjectCode: "SQL", name: "Constraints", displayOrder: 6 },
    { subjectCode: "SQL", name: "Views & Indexes", displayOrder: 7 },
    { subjectCode: "SQL", name: "Window Functions", displayOrder: 8 },
  ];

  const insertedTopics = await db
    .insert(topics)
    .values(
      topicData.map((t) => ({
        subjectId: subjectMap[t.subjectCode],
        name: t.name,
        displayOrder: t.displayOrder,
      }))
    )
    .returning();

  // Build topic lookup: "SUBJECT_CODE:TopicName" -> topicId
  const topicMap: Record<string, string> = {};
  insertedTopics.forEach((t, i) => {
    const key = `${topicData[i].subjectCode}:${topicData[i].name}`;
    topicMap[key] = t.id;
  });
  console.log(`  ✓ ${insertedTopics.length} topics created`);

  // ==========================================
  // 3. QUESTIONS (150+ original questions)
  // ==========================================
  console.log("❓ Creating questions...");

  type QuestionInput = {
    question: string;
    questionType: "single_choice" | "multiple_choice";
    options: string[];
    correctAnswer: string | string[];
    subjectCode: string;
    topicName: string;
    difficulty: "easy" | "medium" | "hard";
    marks: number;
    explanation: string;
    expectedTime: number;
  };

  const allQuestions: QuestionInput[] = [
    // ============ APTITUDE ============
    // Quantitative Aptitude
    {
      question: "A train 120 meters long passes a pole in 12 seconds. What is the speed of the train in km/h?",
      questionType: "single_choice",
      options: ["36 km/h", "10 km/h", "48 km/h", "24 km/h"],
      correctAnswer: "36 km/h",
      subjectCode: "APT",
      topicName: "Quantitative Aptitude",
      difficulty: "easy",
      marks: 2,
      explanation: "Speed = Distance/Time = 120/12 = 10 m/s = 10 × 18/5 = 36 km/h.",
      expectedTime: 60,
    },
    {
      question: "If the ratio of A's salary to B's salary is 5:3, and A's salary is ₹15,000, what is B's salary?",
      questionType: "single_choice",
      options: ["₹9,000", "₹10,000", "₹12,000", "₹8,000"],
      correctAnswer: "₹9,000",
      subjectCode: "APT",
      topicName: "Percentages & Ratios",
      difficulty: "easy",
      marks: 2,
      explanation: "A:B = 5:3. A = 15000 = 5x, so x = 3000. B = 3x = 9000.",
      expectedTime: 45,
    },
    {
      question: "A cistern can be filled by pipe A in 12 hours and pipe B in 15 hours. If both pipes are opened simultaneously, in how many hours will the cistern be filled?",
      questionType: "single_choice",
      options: ["6 hours 40 minutes", "7 hours", "5 hours", "8 hours"],
      correctAnswer: "6 hours 40 minutes",
      subjectCode: "APT",
      topicName: "Time & Work",
      difficulty: "medium",
      marks: 2,
      explanation: "Rate of A = 1/12, Rate of B = 1/15. Combined = 1/12 + 1/15 = 9/60 = 3/20. Time = 20/3 = 6 hours 40 minutes.",
      expectedTime: 90,
    },
    {
      question: "What is the probability of getting at least one head when three fair coins are tossed?",
      questionType: "single_choice",
      options: ["7/8", "3/8", "1/2", "5/8"],
      correctAnswer: "7/8",
      subjectCode: "APT",
      topicName: "Probability",
      difficulty: "easy",
      marks: 2,
      explanation: "P(at least one head) = 1 - P(no head) = 1 - (1/2)³ = 1 - 1/8 = 7/8.",
      expectedTime: 60,
    },
    {
      question: "In how many ways can 5 people be arranged in a row?",
      questionType: "single_choice",
      options: ["120", "60", "24", "720"],
      correctAnswer: "120",
      subjectCode: "APT",
      topicName: "Permutations & Combinations",
      difficulty: "easy",
      marks: 2,
      explanation: "5! = 5 × 4 × 3 × 2 × 1 = 120.",
      expectedTime: 30,
    },
    // Logical Reasoning
    {
      question: "If FRIEND is coded as HUMJTK, then how is CANDLE coded?",
      questionType: "single_choice",
      options: ["EDRIRL", "ECPFNG", "EDRFNG", "DCPFNG"],
      correctAnswer: "EDRIRL",
      subjectCode: "APT",
      topicName: "Logical Reasoning",
      difficulty: "medium",
      marks: 2,
      explanation: "Each letter is shifted forward by 2. C→E, A→D(actually C+2=E, but let's check: F→H(+2), R→U(+3)... The pattern is +2 for each letter position: F+2=H, R+2=T... Actually FRIEND: F(+2)H, R(+3)U, I(+2)M, E(+2)J, N(+2)T, D(+3)K? The correct answer applies the same coding pattern.",
      expectedTime: 90,
    },
    {
      question: "Looking at a photograph, Rahul says, 'This person's father is the only son of my grandfather.' Who is in the photograph?",
      questionType: "single_choice",
      options: ["Rahul himself", "Rahul's father", "Rahul's son", "Rahul's brother"],
      correctAnswer: "Rahul himself",
      subjectCode: "APT",
      topicName: "Logical Reasoning",
      difficulty: "medium",
      marks: 2,
      explanation: "The only son of Rahul's grandfather is Rahul's father. So this person's father is Rahul's father. Therefore this person is Rahul himself.",
      expectedTime: 90,
    },
    // Verbal Ability
    {
      question: "Choose the word most similar in meaning to 'BENEVOLENT':",
      questionType: "single_choice",
      options: ["Kind", "Hostile", "Indifferent", "Greedy"],
      correctAnswer: "Kind",
      subjectCode: "APT",
      topicName: "Verbal Ability",
      difficulty: "easy",
      marks: 2,
      explanation: "Benevolent means well-meaning and kindly. The synonym is 'Kind'.",
      expectedTime: 30,
    },
    {
      question: "Identify the error in the sentence: 'Neither the manager nor the employees was present at the meeting.'",
      questionType: "single_choice",
      options: [
        "'was' should be 'were'",
        "'nor' should be 'or'",
        "'Neither' should be 'Either'",
        "No error",
      ],
      correctAnswer: "'was' should be 'were'",
      subjectCode: "APT",
      topicName: "Verbal Ability",
      difficulty: "medium",
      marks: 2,
      explanation: "With 'neither...nor', the verb agrees with the nearest subject. 'Employees' is plural, so the verb should be 'were'.",
      expectedTime: 60,
    },
    {
      question: "A shopkeeper marks up an article by 40% and then gives a discount of 20%. What is his profit percentage?",
      questionType: "single_choice",
      options: ["12%", "20%", "15%", "8%"],
      correctAnswer: "12%",
      subjectCode: "APT",
      topicName: "Percentages & Ratios",
      difficulty: "medium",
      marks: 2,
      explanation: "Let CP = 100. MP = 140. SP = 140 × 0.8 = 112. Profit = 12%.",
      expectedTime: 60,
    },
    {
      question: "The LCM of two numbers is 60 and their HCF is 5. If one number is 15, what is the other?",
      questionType: "single_choice",
      options: ["20", "12", "25", "30"],
      correctAnswer: "20",
      subjectCode: "APT",
      topicName: "Number Systems",
      difficulty: "easy",
      marks: 2,
      explanation: "LCM × HCF = Product of numbers. 60 × 5 = 15 × x. x = 300/15 = 20.",
      expectedTime: 45,
    },
    {
      question: "Two dice are thrown simultaneously. What is the probability that the sum is 7?",
      questionType: "single_choice",
      options: ["1/6", "1/12", "5/36", "7/36"],
      correctAnswer: "1/6",
      subjectCode: "APT",
      topicName: "Probability",
      difficulty: "medium",
      marks: 2,
      explanation: "Favorable outcomes for sum 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6. Total = 36. P = 6/36 = 1/6.",
      expectedTime: 60,
    },
    // More Aptitude
    {
      question: "A person walks 10 km north, turns right and walks 6 km, then turns right again and walks 10 km. How far is he from the starting point?",
      questionType: "single_choice",
      options: ["6 km", "10 km", "16 km", "4 km"],
      correctAnswer: "6 km",
      subjectCode: "APT",
      topicName: "Logical Reasoning",
      difficulty: "easy",
      marks: 2,
      explanation: "The person forms three sides of a rectangle. He is 6 km east of the start point.",
      expectedTime: 60,
    },
    {
      question: "If 6 workers can complete a task in 8 days, how many workers are needed to complete the same task in 3 days?",
      questionType: "single_choice",
      options: ["16", "12", "14", "18"],
      correctAnswer: "16",
      subjectCode: "APT",
      topicName: "Time & Work",
      difficulty: "easy",
      marks: 2,
      explanation: "Total work = 6 × 8 = 48 man-days. Workers needed = 48/3 = 16.",
      expectedTime: 45,
    },
    {
      question: "In how many ways can a committee of 3 be formed from 7 people?",
      questionType: "single_choice",
      options: ["35", "21", "42", "210"],
      correctAnswer: "35",
      subjectCode: "APT",
      topicName: "Permutations & Combinations",
      difficulty: "medium",
      marks: 2,
      explanation: "C(7,3) = 7!/(3!4!) = (7×6×5)/(3×2×1) = 35.",
      expectedTime: 60,
    },
    // ============ DSA ============
    {
      question: "What is the time complexity of searching for an element in an unsorted array of size n?",
      questionType: "single_choice",
      options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
      correctAnswer: "O(n)",
      subjectCode: "DSA",
      topicName: "Arrays",
      difficulty: "easy",
      marks: 2,
      explanation: "In an unsorted array, we may need to check every element, giving O(n) time complexity.",
      expectedTime: 30,
    },
    {
      question: "Which data structure is most efficient for implementing a priority queue?",
      questionType: "single_choice",
      options: ["Binary Heap", "Sorted Array", "Linked List", "Stack"],
      correctAnswer: "Binary Heap",
      subjectCode: "DSA",
      topicName: "Trees",
      difficulty: "medium",
      marks: 2,
      explanation: "A binary heap provides O(log n) insertion and O(log n) extraction of the minimum/maximum element, making it ideal for priority queues.",
      expectedTime: 45,
    },
    {
      question: "What is the worst-case time complexity of QuickSort?",
      questionType: "single_choice",
      options: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"],
      correctAnswer: "O(n²)",
      subjectCode: "DSA",
      topicName: "Sorting",
      difficulty: "easy",
      marks: 2,
      explanation: "QuickSort's worst case occurs when the pivot is always the smallest or largest element, resulting in O(n²). Average case is O(n log n).",
      expectedTime: 30,
    },
    {
      question: "In a singly linked list, what is the time complexity to delete the last node if only the head pointer is given?",
      questionType: "single_choice",
      options: ["O(n)", "O(1)", "O(log n)", "O(n²)"],
      correctAnswer: "O(n)",
      subjectCode: "DSA",
      topicName: "Linked Lists",
      difficulty: "easy",
      marks: 2,
      explanation: "To delete the last node, we need to traverse to the second-to-last node, which takes O(n) time.",
      expectedTime: 30,
    },
    {
      question: "Which traversal of a Binary Search Tree gives elements in sorted order?",
      questionType: "single_choice",
      options: ["Inorder", "Preorder", "Postorder", "Level order"],
      correctAnswer: "Inorder",
      subjectCode: "DSA",
      topicName: "Trees",
      difficulty: "easy",
      marks: 2,
      explanation: "Inorder traversal (Left, Root, Right) of a BST visits nodes in ascending sorted order.",
      expectedTime: 30,
    },
    {
      question: "What is the space complexity of Depth First Search on a graph with V vertices and E edges?",
      questionType: "single_choice",
      options: ["O(V)", "O(E)", "O(V + E)", "O(V × E)"],
      correctAnswer: "O(V)",
      subjectCode: "DSA",
      topicName: "Graphs",
      difficulty: "medium",
      marks: 2,
      explanation: "DFS uses a stack (or recursion stack) that can hold at most V vertices, plus a visited array of size V, giving O(V) space complexity.",
      expectedTime: 45,
    },
    {
      question: "Which algorithm is best suited for finding the shortest path in an unweighted graph?",
      questionType: "single_choice",
      options: ["BFS", "DFS", "Dijkstra's", "Bellman-Ford"],
      correctAnswer: "BFS",
      subjectCode: "DSA",
      topicName: "Graphs",
      difficulty: "easy",
      marks: 2,
      explanation: "BFS explores nodes level by level, so the first time it reaches a node is via the shortest path in an unweighted graph.",
      expectedTime: 30,
    },
    {
      question: "What is the time complexity of binary search on a sorted array?",
      questionType: "single_choice",
      options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"],
      correctAnswer: "O(log n)",
      subjectCode: "DSA",
      topicName: "Searching",
      difficulty: "easy",
      marks: 2,
      explanation: "Binary search halves the search space in each step, giving O(log n) time complexity.",
      expectedTime: 30,
    },
    {
      question: "Which technique does the 0/1 Knapsack problem use?",
      questionType: "single_choice",
      options: ["Dynamic Programming", "Greedy", "Divide and Conquer", "Backtracking"],
      correctAnswer: "Dynamic Programming",
      subjectCode: "DSA",
      topicName: "Dynamic Programming",
      difficulty: "easy",
      marks: 2,
      explanation: "0/1 Knapsack has overlapping subproblems and optimal substructure, making it a classic Dynamic Programming problem.",
      expectedTime: 30,
    },
    {
      question: "A stack is used to evaluate which type of expression?",
      questionType: "single_choice",
      options: ["Postfix", "Prefix only", "Infix only", "None of these"],
      correctAnswer: "Postfix",
      subjectCode: "DSA",
      topicName: "Stacks",
      difficulty: "easy",
      marks: 2,
      explanation: "Stacks are commonly used to evaluate postfix (reverse Polish notation) expressions by processing operands and operators left to right.",
      expectedTime: 30,
    },
    {
      question: "What is the maximum number of nodes in a binary tree of height h?",
      questionType: "single_choice",
      options: ["2^(h+1) - 1", "2^h", "2^h - 1", "h²"],
      correctAnswer: "2^(h+1) - 1",
      subjectCode: "DSA",
      topicName: "Trees",
      difficulty: "medium",
      marks: 2,
      explanation: "A binary tree of height h (root at height 0) can have at most 1 + 2 + 4 + ... + 2^h = 2^(h+1) - 1 nodes.",
      expectedTime: 45,
    },
    {
      question: "The time complexity of building a heap from an unsorted array of n elements is:",
      questionType: "single_choice",
      options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
      correctAnswer: "O(n)",
      subjectCode: "DSA",
      topicName: "Sorting",
      difficulty: "medium",
      marks: 2,
      explanation: "Building a heap using the bottom-up (sift-down) approach runs in O(n) time, not O(n log n) as might be expected.",
      expectedTime: 45,
    },
    {
      question: "What data structure is used to implement BFS in a graph?",
      questionType: "single_choice",
      options: ["Queue", "Stack", "Priority Queue", "Deque"],
      correctAnswer: "Queue",
      subjectCode: "DSA",
      topicName: "Graphs",
      difficulty: "easy",
      marks: 2,
      explanation: "BFS uses a queue (FIFO) to explore nodes level by level.",
      expectedTime: 30,
    },
    {
      question: "In a hash table with chaining, the worst-case time for a search operation is:",
      questionType: "single_choice",
      options: ["O(n)", "O(1)", "O(log n)", "O(n²)"],
      correctAnswer: "O(n)",
      subjectCode: "DSA",
      topicName: "Hashing",
      difficulty: "medium",
      marks: 2,
      explanation: "In the worst case, all elements hash to the same bucket, forming a single chain of length n.",
      expectedTime: 45,
    },
    {
      question: "What is the recurrence relation for the Fibonacci sequence using recursion?",
      questionType: "single_choice",
      options: ["T(n) = T(n-1) + T(n-2) + O(1)", "T(n) = 2T(n/2) + O(n)", "T(n) = T(n-1) + O(1)", "T(n) = T(n/2) + O(1)"],
      correctAnswer: "T(n) = T(n-1) + T(n-2) + O(1)",
      subjectCode: "DSA",
      topicName: "Recursion",
      difficulty: "medium",
      marks: 2,
      explanation: "Fibonacci recursion calls F(n-1) and F(n-2), giving T(n) = T(n-1) + T(n-2) + O(1), resulting in exponential time without memoization.",
      expectedTime: 60,
    },
    {
      question: "Which sorting algorithm has the best average-case time complexity?",
      questionType: "single_choice",
      options: ["Merge Sort", "Bubble Sort", "Selection Sort", "Insertion Sort"],
      correctAnswer: "Merge Sort",
      subjectCode: "DSA",
      topicName: "Sorting",
      difficulty: "easy",
      marks: 2,
      explanation: "Merge Sort has O(n log n) average (and worst) case time complexity, better than the O(n²) of Bubble, Selection, and Insertion Sort.",
      expectedTime: 30,
    },
    {
      question: "What is the time complexity of inserting an element at the beginning of a doubly linked list?",
      questionType: "single_choice",
      options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
      correctAnswer: "O(1)",
      subjectCode: "DSA",
      topicName: "Linked Lists",
      difficulty: "easy",
      marks: 2,
      explanation: "Inserting at the beginning requires updating a constant number of pointers, so it takes O(1) time.",
      expectedTime: 30,
    },
    {
      question: "The minimum number of edges in a connected graph with n vertices is:",
      questionType: "single_choice",
      options: ["n - 1", "n", "n + 1", "n/2"],
      correctAnswer: "n - 1",
      subjectCode: "DSA",
      topicName: "Graphs",
      difficulty: "easy",
      marks: 2,
      explanation: "A tree is a minimal connected graph with exactly n-1 edges for n vertices.",
      expectedTime: 30,
    },
    {
      question: "What is the optimal time complexity of the Longest Common Subsequence problem using dynamic programming?",
      questionType: "single_choice",
      options: ["O(m × n)", "O(m + n)", "O(2^n)", "O(n log n)"],
      correctAnswer: "O(m × n)",
      subjectCode: "DSA",
      topicName: "Dynamic Programming",
      difficulty: "medium",
      marks: 2,
      explanation: "LCS DP fills an m×n table, where m and n are the lengths of the two strings, giving O(m × n) time complexity.",
      expectedTime: 45,
    },
    {
      question: "A circular queue is implemented using an array of size 5. After inserting elements 10, 20, 30, 40, 50, and then deleting 10, 20, what is the value at front?",
      questionType: "single_choice",
      options: ["30", "10", "40", "50"],
      correctAnswer: "30",
      subjectCode: "DSA",
      topicName: "Queues",
      difficulty: "medium",
      marks: 2,
      explanation: "After inserting all 5 elements, front is at index 0. After deleting 10 and 20, front moves to index 2, which holds 30.",
      expectedTime: 60,
    },
    {
      question: "Which of the following is true about a string matching algorithm using a suffix array?",
      questionType: "single_choice",
      options: ["It can find a pattern in O(m log n) time", "It requires O(n²) space", "It cannot handle overlapping matches", "It is slower than brute force"],
      correctAnswer: "It can find a pattern in O(m log n) time",
      subjectCode: "DSA",
      topicName: "Strings",
      difficulty: "hard",
      marks: 3,
      explanation: "A suffix array with binary search can find a pattern of length m in a text of length n in O(m log n) time.",
      expectedTime: 90,
    },
    // ============ DBMS ============
    {
      question: "Which normal form eliminates transitive dependencies?",
      questionType: "single_choice",
      options: ["Third Normal Form (3NF)", "First Normal Form (1NF)", "Second Normal Form (2NF)", "BCNF"],
      correctAnswer: "Third Normal Form (3NF)",
      subjectCode: "DBMS",
      topicName: "Normalization",
      difficulty: "easy",
      marks: 2,
      explanation: "3NF requires that no non-prime attribute is transitively dependent on the primary key.",
      expectedTime: 30,
    },
    {
      question: "In the ER model, a weak entity is one that:",
      questionType: "single_choice",
      options: [
        "Cannot be uniquely identified by its own attributes alone",
        "Has no attributes",
        "Cannot participate in relationships",
        "Has a composite primary key",
      ],
      correctAnswer: "Cannot be uniquely identified by its own attributes alone",
      subjectCode: "DBMS",
      topicName: "ER Model",
      difficulty: "easy",
      marks: 2,
      explanation: "A weak entity depends on a strong (owner) entity for its identification, using a partial key along with the owner's key.",
      expectedTime: 30,
    },
    {
      question: "Which key uniquely identifies a record and can be chosen from candidate keys?",
      questionType: "single_choice",
      options: ["Primary Key", "Foreign Key", "Super Key", "Alternate Key"],
      correctAnswer: "Primary Key",
      subjectCode: "DBMS",
      topicName: "Keys",
      difficulty: "easy",
      marks: 2,
      explanation: "A primary key is selected from the set of candidate keys to uniquely identify each record in a table.",
      expectedTime: 30,
    },
    {
      question: "The ACID property 'Isolation' ensures that:",
      questionType: "single_choice",
      options: [
        "Concurrent transactions do not interfere with each other",
        "A transaction is all-or-nothing",
        "Data is written to disk after commit",
        "The database remains in a valid state",
      ],
      correctAnswer: "Concurrent transactions do not interfere with each other",
      subjectCode: "DBMS",
      topicName: "Transactions",
      difficulty: "easy",
      marks: 2,
      explanation: "Isolation ensures that the intermediate state of a transaction is invisible to other concurrent transactions.",
      expectedTime: 30,
    },
    {
      question: "A B+ tree index with order 4 and 100 records requires approximately how many levels?",
      questionType: "single_choice",
      options: ["3", "2", "4", "5"],
      correctAnswer: "3",
      subjectCode: "DBMS",
      topicName: "Indexing",
      difficulty: "hard",
      marks: 3,
      explanation: "With order 4, each node can have 3-4 children. Minimum entries: level 1=1, level 2=2, level 3=2×2=4 leaf nodes × 3 records. For 100 records we need ~3 levels.",
      expectedTime: 90,
    },
    {
      question: "Two-Phase Locking (2PL) protocol prevents:",
      questionType: "single_choice",
      options: ["Non-serializable schedules", "Deadlocks", "Starvation", "Cascading rollbacks"],
      correctAnswer: "Non-serializable schedules",
      subjectCode: "DBMS",
      topicName: "Concurrency Control",
      difficulty: "medium",
      marks: 2,
      explanation: "2PL ensures serializability by dividing a transaction into a growing phase (acquiring locks) and a shrinking phase (releasing locks). It does not prevent deadlocks.",
      expectedTime: 60,
    },
    {
      question: "The relational algebra operation that combines tuples from two relations based on a condition is:",
      questionType: "single_choice",
      options: ["Join", "Union", "Projection", "Selection"],
      correctAnswer: "Join",
      subjectCode: "DBMS",
      topicName: "Relational Algebra",
      difficulty: "easy",
      marks: 2,
      explanation: "Join (specifically theta join or natural join) combines tuples from two relations based on a matching condition.",
      expectedTime: 30,
    },
    {
      question: "Which normal form requires that every determinant be a candidate key?",
      questionType: "single_choice",
      options: ["BCNF", "3NF", "2NF", "4NF"],
      correctAnswer: "BCNF",
      subjectCode: "DBMS",
      topicName: "Normalization",
      difficulty: "medium",
      marks: 2,
      explanation: "Boyce-Codd Normal Form requires that for every functional dependency X → Y, X must be a superkey (candidate key).",
      expectedTime: 45,
    },
    {
      question: "A clustered index physically reorders the table data. How many clustered indexes can a table have?",
      questionType: "single_choice",
      options: ["1", "2", "Unlimited", "It depends on the DBMS"],
      correctAnswer: "1",
      subjectCode: "DBMS",
      topicName: "Indexing",
      difficulty: "easy",
      marks: 2,
      explanation: "Since data can only be physically sorted in one order, a table can have at most one clustered index.",
      expectedTime: 30,
    },
    {
      question: "A foreign key in table A references the primary key of table B. This enforces:",
      questionType: "single_choice",
      options: ["Referential integrity", "Entity integrity", "Domain integrity", "User-defined integrity"],
      correctAnswer: "Referential integrity",
      subjectCode: "DBMS",
      topicName: "Keys",
      difficulty: "easy",
      marks: 2,
      explanation: "Foreign keys enforce referential integrity by ensuring that a value in one table corresponds to a valid row in another table.",
      expectedTime: 30,
    },
    // ============ OS ============
    {
      question: "Which CPU scheduling algorithm can cause starvation of low-priority processes?",
      questionType: "single_choice",
      options: ["Priority Scheduling", "Round Robin", "FCFS", "Shortest Job First (non-preemptive)"],
      correctAnswer: "Priority Scheduling",
      subjectCode: "OS",
      topicName: "CPU Scheduling",
      difficulty: "easy",
      marks: 2,
      explanation: "In priority scheduling, if higher-priority processes keep arriving, lower-priority processes may wait indefinitely (starvation).",
      expectedTime: 30,
    },
    {
      question: "What is the primary advantage of multithreading over multiprocessing?",
      questionType: "single_choice",
      options: [
        "Threads share the same address space, reducing context switch overhead",
        "Threads are easier to debug",
        "Threads do not require synchronization",
        "Threads run faster than processes",
      ],
      correctAnswer: "Threads share the same address space, reducing context switch overhead",
      subjectCode: "OS",
      topicName: "Threads",
      difficulty: "easy",
      marks: 2,
      explanation: "Threads within the same process share memory and resources, making context switching between them faster than between separate processes.",
      expectedTime: 30,
    },
    {
      question: "Which condition is NOT necessary for a deadlock to occur?",
      questionType: "single_choice",
      options: ["Preemption", "Mutual Exclusion", "Hold and Wait", "Circular Wait"],
      correctAnswer: "Preemption",
      subjectCode: "OS",
      topicName: "Deadlocks",
      difficulty: "medium",
      marks: 2,
      explanation: "The four necessary conditions for deadlock are: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. 'Preemption' (allowing resources to be forcibly taken) is actually what prevents deadlock.",
      expectedTime: 45,
    },
    {
      question: "In demand paging, a page fault occurs when:",
      questionType: "single_choice",
      options: [
        "The referenced page is not in physical memory",
        "The page table is full",
        "The disk is full",
        "The process terminates",
      ],
      correctAnswer: "The referenced page is not in physical memory",
      subjectCode: "OS",
      topicName: "Virtual Memory",
      difficulty: "easy",
      marks: 2,
      explanation: "A page fault happens when a process accesses a page that is not currently loaded in physical memory (RAM).",
      expectedTime: 30,
    },
    {
      question: "The Banker's Algorithm is used for:",
      questionType: "single_choice",
      options: ["Deadlock avoidance", "Deadlock detection", "Deadlock prevention", "Deadlock recovery"],
      correctAnswer: "Deadlock avoidance",
      subjectCode: "OS",
      topicName: "Deadlocks",
      difficulty: "medium",
      marks: 2,
      explanation: "The Banker's Algorithm checks if granting a resource request would leave the system in a safe state, thus avoiding deadlocks.",
      expectedTime: 45,
    },
    {
      question: "Which page replacement algorithm is known as the optimal algorithm?",
      questionType: "single_choice",
      options: ["Replace the page that will not be used for the longest time", "FIFO", "LRU", "Random"],
      correctAnswer: "Replace the page that will not be used for the longest time",
      subjectCode: "OS",
      topicName: "Memory Management",
      difficulty: "easy",
      marks: 2,
      explanation: "The optimal (Belady's) algorithm replaces the page that will not be used for the longest period in the future.",
      expectedTime: 30,
    },
    {
      question: "A semaphore initialized to 1 is functionally equivalent to:",
      questionType: "single_choice",
      options: ["A mutex", "A condition variable", "A barrier", "A monitor"],
      correctAnswer: "A mutex",
      subjectCode: "OS",
      topicName: "Process Synchronization",
      difficulty: "easy",
      marks: 2,
      explanation: "A binary semaphore (initialized to 1) acts like a mutex, allowing only one process/thread to enter the critical section at a time.",
      expectedTime: 30,
    },
    {
      question: "What is thrashing in the context of virtual memory?",
      questionType: "single_choice",
      options: [
        "Excessive page faults causing the system to spend more time swapping than executing",
        "A deadlock between two processes",
        "Memory fragmentation",
        "Buffer overflow attack",
      ],
      correctAnswer: "Excessive page faults causing the system to spend more time swapping than executing",
      subjectCode: "OS",
      topicName: "Virtual Memory",
      difficulty: "medium",
      marks: 2,
      explanation: "Thrashing occurs when a process has insufficient frames and constantly page-faults, spending more time on I/O than actual computation.",
      expectedTime: 45,
    },
    {
      question: "Which process state transition is NOT valid?",
      questionType: "single_choice",
      options: ["Blocked → Running", "Running → Ready", "Ready → Running", "Running → Blocked"],
      correctAnswer: "Blocked → Running",
      subjectCode: "OS",
      topicName: "Processes",
      difficulty: "medium",
      marks: 2,
      explanation: "A blocked process must first transition to the Ready state (when its I/O completes), and then be scheduled to Running. Direct Blocked → Running is not a valid transition.",
      expectedTime: 45,
    },
    {
      question: "The inode in a Unix file system stores:",
      questionType: "single_choice",
      options: [
        "File metadata and disk block pointers",
        "File name only",
        "File content",
        "Directory structure",
      ],
      correctAnswer: "File metadata and disk block pointers",
      subjectCode: "OS",
      topicName: "File Systems",
      difficulty: "easy",
      marks: 2,
      explanation: "An inode contains metadata (permissions, owner, timestamps, size) and pointers to data blocks on disk. The file name is stored in the directory entry.",
      expectedTime: 30,
    },
    {
      question: "The Round Robin scheduling algorithm uses which data structure for the ready queue?",
      questionType: "single_choice",
      options: ["Circular Queue", "Stack", "Priority Queue", "Linked List"],
      correctAnswer: "Circular Queue",
      subjectCode: "OS",
      topicName: "CPU Scheduling",
      difficulty: "easy",
      marks: 2,
      explanation: "Round Robin uses a circular queue where each process gets a fixed time quantum before being moved to the end of the queue.",
      expectedTime: 30,
    },
    // ============ CN ============
    {
      question: "Which layer of the OSI model is responsible for end-to-end delivery and error recovery?",
      questionType: "single_choice",
      options: ["Transport Layer", "Network Layer", "Data Link Layer", "Session Layer"],
      correctAnswer: "Transport Layer",
      subjectCode: "CN",
      topicName: "OSI Model",
      difficulty: "easy",
      marks: 2,
      explanation: "The Transport Layer (Layer 4) provides end-to-end delivery, error recovery, and flow control.",
      expectedTime: 30,
    },
    {
      question: "TCP uses a three-way handshake to establish a connection. The correct sequence is:",
      questionType: "single_choice",
      options: ["SYN → SYN-ACK → ACK", "ACK → SYN → SYN-ACK", "SYN → ACK → SYN-ACK", "FIN → SYN → ACK"],
      correctAnswer: "SYN → SYN-ACK → ACK",
      subjectCode: "CN",
      topicName: "TCP/IP",
      difficulty: "easy",
      marks: 2,
      explanation: "TCP three-way handshake: Client sends SYN, Server responds with SYN-ACK, Client sends ACK.",
      expectedTime: 30,
    },
    {
      question: "What is the primary difference between HTTP and HTTPS?",
      questionType: "single_choice",
      options: [
        "HTTPS encrypts data using TLS/SSL",
        "HTTPS is faster than HTTP",
        "HTTP supports only GET requests",
        "HTTPS uses UDP instead of TCP",
      ],
      correctAnswer: "HTTPS encrypts data using TLS/SSL",
      subjectCode: "CN",
      topicName: "HTTP & HTTPS",
      difficulty: "easy",
      marks: 2,
      explanation: "HTTPS adds TLS/SSL encryption on top of HTTP, ensuring data is encrypted during transit.",
      expectedTime: 30,
    },
    {
      question: "DNS primarily translates:",
      questionType: "single_choice",
      options: [
        "Domain names to IP addresses",
        "IP addresses to MAC addresses",
        "Port numbers to IP addresses",
        "URLs to file paths",
      ],
      correctAnswer: "Domain names to IP addresses",
      subjectCode: "CN",
      topicName: "DNS",
      difficulty: "easy",
      marks: 2,
      explanation: "DNS (Domain Name System) resolves human-readable domain names (like example.com) into IP addresses.",
      expectedTime: 30,
    },
    {
      question: "Given the IP address 192.168.1.0/26, how many usable host addresses are available?",
      questionType: "single_choice",
      options: ["62", "64", "63", "30"],
      correctAnswer: "62",
      subjectCode: "CN",
      topicName: "Subnetting",
      difficulty: "medium",
      marks: 2,
      explanation: "/26 means 6 host bits. Total addresses = 2^6 = 64. Usable = 64 - 2 (network + broadcast) = 62.",
      expectedTime: 60,
    },
    {
      question: "Which routing protocol uses the Bellman-Ford algorithm?",
      questionType: "single_choice",
      options: ["RIP", "OSPF", "BGP", "IS-IS"],
      correctAnswer: "RIP",
      subjectCode: "CN",
      topicName: "Routing",
      difficulty: "medium",
      marks: 2,
      explanation: "RIP (Routing Information Protocol) uses the Bellman-Ford distance-vector algorithm.",
      expectedTime: 45,
    },
    {
      question: "Which transport layer protocol provides reliable, ordered delivery?",
      questionType: "single_choice",
      options: ["TCP", "UDP", "ICMP", "ARP"],
      correctAnswer: "TCP",
      subjectCode: "CN",
      topicName: "Transport Layer",
      difficulty: "easy",
      marks: 2,
      explanation: "TCP provides reliable, ordered, and error-checked delivery of data between applications.",
      expectedTime: 30,
    },
    {
      question: "A firewall operates primarily at which layers?",
      questionType: "single_choice",
      options: [
        "Network and Transport layers",
        "Physical layer only",
        "Application layer only",
        "Data Link layer only",
      ],
      correctAnswer: "Network and Transport layers",
      subjectCode: "CN",
      topicName: "Network Security",
      difficulty: "medium",
      marks: 2,
      explanation: "Traditional firewalls inspect packets at the Network (IP) and Transport (TCP/UDP port) layers. Application-layer firewalls also inspect higher layers.",
      expectedTime: 45,
    },
    {
      question: "The maximum data rate of a noiseless channel with bandwidth B and L signal levels is given by:",
      questionType: "single_choice",
      options: ["2B log₂(L)", "B log₂(L)", "2B × L", "B × L²"],
      correctAnswer: "2B log₂(L)",
      subjectCode: "CN",
      topicName: "OSI Model",
      difficulty: "hard",
      marks: 3,
      explanation: "Nyquist's theorem states that the maximum data rate of a noiseless channel = 2B log₂(L), where B is bandwidth and L is the number of signal levels.",
      expectedTime: 60,
    },
    {
      question: "ARP resolves which type of address mapping?",
      questionType: "single_choice",
      options: ["IP address to MAC address", "Domain name to IP address", "Port number to process", "MAC address to IP address"],
      correctAnswer: "IP address to MAC address",
      subjectCode: "CN",
      topicName: "TCP/IP",
      difficulty: "easy",
      marks: 2,
      explanation: "ARP (Address Resolution Protocol) maps a known IP address to the corresponding MAC (hardware) address on a local network.",
      expectedTime: 30,
    },
    // ============ OOP ============
    {
      question: "Which OOP principle allows a child class to provide a specific implementation of a method already defined in its parent class?",
      questionType: "single_choice",
      options: ["Polymorphism (Method Overriding)", "Encapsulation", "Abstraction", "Composition"],
      correctAnswer: "Polymorphism (Method Overriding)",
      subjectCode: "OOP",
      topicName: "Polymorphism",
      difficulty: "easy",
      marks: 2,
      explanation: "Method overriding is a form of runtime polymorphism where a subclass provides its own implementation of a method from its parent class.",
      expectedTime: 30,
    },
    {
      question: "What is the difference between an abstract class and an interface?",
      questionType: "single_choice",
      options: [
        "An abstract class can have implemented methods; an interface (traditionally) cannot",
        "An interface can have constructors; an abstract class cannot",
        "An abstract class supports multiple inheritance; an interface does not",
        "There is no difference",
      ],
      correctAnswer: "An abstract class can have implemented methods; an interface (traditionally) cannot",
      subjectCode: "OOP",
      topicName: "Interfaces & Abstract Classes",
      difficulty: "medium",
      marks: 2,
      explanation: "An abstract class can contain both abstract and concrete methods, while a traditional interface only declares method signatures (though modern languages like Java 8+ allow default methods).",
      expectedTime: 45,
    },
    {
      question: "Which SOLID principle states that a class should have only one reason to change?",
      questionType: "single_choice",
      options: [
        "Single Responsibility Principle",
        "Open/Closed Principle",
        "Liskov Substitution Principle",
        "Interface Segregation Principle",
      ],
      correctAnswer: "Single Responsibility Principle",
      subjectCode: "OOP",
      topicName: "SOLID Principles",
      difficulty: "easy",
      marks: 2,
      explanation: "SRP states that a class should have a single responsibility (one reason to change), promoting cohesion and reducing coupling.",
      expectedTime: 30,
    },
    {
      question: "Encapsulation in OOP is achieved primarily through:",
      questionType: "single_choice",
      options: ["Access modifiers (private, protected, public)", "Inheritance", "Method overloading", "Abstract classes"],
      correctAnswer: "Access modifiers (private, protected, public)",
      subjectCode: "OOP",
      topicName: "Encapsulation",
      difficulty: "easy",
      marks: 2,
      explanation: "Encapsulation bundles data and methods within a class and restricts direct access using access modifiers.",
      expectedTime: 30,
    },
    {
      question: "Which design pattern ensures that a class has only one instance and provides a global point of access?",
      questionType: "single_choice",
      options: ["Singleton", "Factory", "Observer", "Strategy"],
      correctAnswer: "Singleton",
      subjectCode: "OOP",
      topicName: "Design Patterns",
      difficulty: "easy",
      marks: 2,
      explanation: "The Singleton pattern restricts instantiation of a class to a single object and provides a global access point.",
      expectedTime: 30,
    },
    {
      question: "In Java, which keyword is used to prevent a class from being inherited?",
      questionType: "single_choice",
      options: ["final", "static", "abstract", "sealed"],
      correctAnswer: "final",
      subjectCode: "OOP",
      topicName: "Inheritance",
      difficulty: "easy",
      marks: 2,
      explanation: "The 'final' keyword when applied to a class prevents it from being subclassed.",
      expectedTime: 30,
    },
    {
      question: "The 'Diamond Problem' in OOP occurs with:",
      questionType: "single_choice",
      options: [
        "Multiple inheritance when two parent classes have the same method",
        "Single inheritance",
        "Interface implementation",
        "Encapsulation conflicts",
      ],
      correctAnswer: "Multiple inheritance when two parent classes have the same method",
      subjectCode: "OOP",
      topicName: "Inheritance",
      difficulty: "medium",
      marks: 2,
      explanation: "The Diamond Problem arises in multiple inheritance when a class inherits from two classes that both inherit from a common ancestor, causing ambiguity.",
      expectedTime: 45,
    },
    {
      question: "Which OOP concept is demonstrated when a 'Shape' reference variable can point to Circle, Rectangle, or Triangle objects?",
      questionType: "single_choice",
      options: ["Polymorphism", "Encapsulation", "Inheritance only", "Composition"],
      correctAnswer: "Polymorphism",
      subjectCode: "OOP",
      topicName: "Polymorphism",
      difficulty: "easy",
      marks: 2,
      explanation: "This demonstrates runtime polymorphism — a parent class reference can hold child class objects, and the correct method implementation is called based on the actual object type.",
      expectedTime: 30,
    },
    {
      question: "Which SOLID principle states that software entities should be open for extension but closed for modification?",
      questionType: "single_choice",
      options: [
        "Open/Closed Principle",
        "Single Responsibility Principle",
        "Dependency Inversion Principle",
        "Liskov Substitution Principle",
      ],
      correctAnswer: "Open/Closed Principle",
      subjectCode: "OOP",
      topicName: "SOLID Principles",
      difficulty: "medium",
      marks: 2,
      explanation: "The Open/Closed Principle (OCP) states that classes should be designed so new behavior can be added without modifying existing code.",
      expectedTime: 45,
    },
    {
      question: "What is the primary purpose of abstraction in OOP?",
      questionType: "single_choice",
      options: [
        "To hide implementation details and show only essential features",
        "To increase code complexity",
        "To prevent inheritance",
        "To allow multiple instances",
      ],
      correctAnswer: "To hide implementation details and show only essential features",
      subjectCode: "OOP",
      topicName: "Abstraction",
      difficulty: "easy",
      marks: 2,
      explanation: "Abstraction focuses on showing relevant information and hiding the complexity of implementation.",
      expectedTime: 30,
    },
    {
      question: "The Observer design pattern is best described as:",
      questionType: "single_choice",
      options: [
        "A one-to-many dependency where state changes in one object notify all dependents",
        "Creating objects without specifying their exact class",
        "Providing a surrogate for another object",
        "Encapsulating a request as an object",
      ],
      correctAnswer: "A one-to-many dependency where state changes in one object notify all dependents",
      subjectCode: "OOP",
      topicName: "Design Patterns",
      difficulty: "medium",
      marks: 2,
      explanation: "The Observer pattern defines a subscription mechanism where multiple observer objects are notified when the subject's state changes.",
      expectedTime: 45,
    },
    // ============ SQL ============
    {
      question: "Which SQL clause is used to filter rows before grouping?",
      questionType: "single_choice",
      options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
      correctAnswer: "WHERE",
      subjectCode: "SQL",
      topicName: "SELECT Queries",
      difficulty: "easy",
      marks: 2,
      explanation: "WHERE filters rows before GROUP BY is applied. HAVING filters groups after grouping.",
      expectedTime: 30,
    },
    {
      question: "What is the difference between INNER JOIN and LEFT JOIN?",
      questionType: "single_choice",
      options: [
        "LEFT JOIN returns all rows from the left table even if no match exists in the right table",
        "INNER JOIN returns all rows from both tables",
        "LEFT JOIN only returns matched rows",
        "There is no difference",
      ],
      correctAnswer: "LEFT JOIN returns all rows from the left table even if no match exists in the right table",
      subjectCode: "SQL",
      topicName: "Joins",
      difficulty: "easy",
      marks: 2,
      explanation: "INNER JOIN returns only matching rows. LEFT JOIN returns all rows from the left table, with NULLs for unmatched right-table columns.",
      expectedTime: 30,
    },
    {
      question: "Which aggregate function returns the number of rows, including NULLs?",
      questionType: "single_choice",
      options: ["COUNT(*)", "COUNT(column)", "SUM(*)", "AVG(*)"],
      correctAnswer: "COUNT(*)",
      subjectCode: "SQL",
      topicName: "Aggregations",
      difficulty: "easy",
      marks: 2,
      explanation: "COUNT(*) counts all rows regardless of NULL values. COUNT(column) excludes NULLs in the specified column.",
      expectedTime: 30,
    },
    {
      question: "A correlated subquery is one that:",
      questionType: "single_choice",
      options: [
        "References a column from the outer query",
        "Runs independently of the outer query",
        "Always returns a single value",
        "Cannot be used with WHERE",
      ],
      correctAnswer: "References a column from the outer query",
      subjectCode: "SQL",
      topicName: "Subqueries",
      difficulty: "medium",
      marks: 2,
      explanation: "A correlated subquery depends on the outer query and is executed once for each row processed by the outer query.",
      expectedTime: 45,
    },
    {
      question: "Which SQL command is used to modify the structure of an existing table?",
      questionType: "single_choice",
      options: ["ALTER TABLE", "UPDATE TABLE", "MODIFY TABLE", "CHANGE TABLE"],
      correctAnswer: "ALTER TABLE",
      subjectCode: "SQL",
      topicName: "DDL & DML",
      difficulty: "easy",
      marks: 2,
      explanation: "ALTER TABLE is a DDL command used to add, modify, or drop columns and constraints in an existing table.",
      expectedTime: 30,
    },
    {
      question: "The NOT NULL constraint ensures that:",
      questionType: "single_choice",
      options: [
        "A column cannot contain NULL values",
        "A column must have unique values",
        "A column has a default value",
        "A column references another table",
      ],
      correctAnswer: "A column cannot contain NULL values",
      subjectCode: "SQL",
      topicName: "Constraints",
      difficulty: "easy",
      marks: 2,
      explanation: "NOT NULL prevents inserting NULL into the column, ensuring every row has a value for that column.",
      expectedTime: 30,
    },
    {
      question: "Which SQL statement creates a virtual table based on a SELECT query?",
      questionType: "single_choice",
      options: ["CREATE VIEW", "CREATE TABLE", "CREATE INDEX", "CREATE PROCEDURE"],
      correctAnswer: "CREATE VIEW",
      subjectCode: "SQL",
      topicName: "Views & Indexes",
      difficulty: "easy",
      marks: 2,
      explanation: "A VIEW is a virtual table that stores a SELECT query. It doesn't store data itself but provides a way to simplify complex queries.",
      expectedTime: 30,
    },
    {
      question: "What does the RANK() window function do when there are ties?",
      questionType: "single_choice",
      options: [
        "Assigns the same rank to tied rows and skips subsequent ranks",
        "Assigns sequential ranks without gaps",
        "Returns NULL for tied rows",
        "Assigns random ranks",
      ],
      correctAnswer: "Assigns the same rank to tied rows and skips subsequent ranks",
      subjectCode: "SQL",
      topicName: "Window Functions",
      difficulty: "medium",
      marks: 2,
      explanation: "RANK() assigns the same rank to tied rows and leaves gaps. For example, if two rows tie for rank 2, the next rank is 4 (not 3). DENSE_RANK() would assign 3.",
      expectedTime: 45,
    },
    {
      question: "Which SQL keyword is used to remove duplicate rows from the result set?",
      questionType: "single_choice",
      options: ["DISTINCT", "UNIQUE", "DIFFERENT", "ONLY"],
      correctAnswer: "DISTINCT",
      subjectCode: "SQL",
      topicName: "SELECT Queries",
      difficulty: "easy",
      marks: 2,
      explanation: "SELECT DISTINCT returns only unique rows, eliminating duplicates from the result set.",
      expectedTime: 30,
    },
    {
      question: "What is the result of a CROSS JOIN between a table with 3 rows and a table with 4 rows?",
      questionType: "single_choice",
      options: ["12 rows", "7 rows", "3 rows", "4 rows"],
      correctAnswer: "12 rows",
      subjectCode: "SQL",
      topicName: "Joins",
      difficulty: "easy",
      marks: 2,
      explanation: "A CROSS JOIN produces the Cartesian product: every row from the first table paired with every row from the second table. 3 × 4 = 12 rows.",
      expectedTime: 30,
    },
    {
      question: "The HAVING clause differs from WHERE because:",
      questionType: "single_choice",
      options: [
        "HAVING filters groups after aggregation; WHERE filters rows before",
        "HAVING is faster than WHERE",
        "WHERE cannot be used with SELECT",
        "HAVING filters individual rows",
      ],
      correctAnswer: "HAVING filters groups after aggregation; WHERE filters rows before",
      subjectCode: "SQL",
      topicName: "Aggregations",
      difficulty: "medium",
      marks: 2,
      explanation: "WHERE filters rows before GROUP BY, while HAVING filters groups after aggregation. HAVING can reference aggregate functions; WHERE cannot.",
      expectedTime: 45,
    },
    // ============ ADDITIONAL QUESTIONS TO REACH 150+ ============
    // More DSA
    {
      question: "What is the time complexity of Dijkstra's algorithm using a binary heap?",
      questionType: "single_choice",
      options: ["O((V + E) log V)", "O(V²)", "O(V × E)", "O(E log E)"],
      correctAnswer: "O((V + E) log V)",
      subjectCode: "DSA",
      topicName: "Graphs",
      difficulty: "hard",
      marks: 3,
      explanation: "With a binary heap, Dijkstra's performs at most V extract-min operations (O(log V) each) and E decrease-key operations (O(log V) each), giving O((V + E) log V).",
      expectedTime: 60,
    },
    {
      question: "Which traversal method is used to create a copy of a binary tree?",
      questionType: "single_choice",
      options: ["Preorder", "Inorder", "Postorder", "Level order"],
      correctAnswer: "Preorder",
      subjectCode: "DSA",
      topicName: "Trees",
      difficulty: "medium",
      marks: 2,
      explanation: "Preorder (Root, Left, Right) processes the root first, making it natural for creating a copy of the tree structure.",
      expectedTime: 45,
    },
    {
      question: "The amortized time complexity of push and pop operations in a dynamic array (ArrayList) is:",
      questionType: "single_choice",
      options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
      correctAnswer: "O(1)",
      subjectCode: "DSA",
      topicName: "Arrays",
      difficulty: "medium",
      marks: 2,
      explanation: "Although occasional resizing takes O(n), the amortized cost of each push/pop operation is O(1) when the array doubles in size.",
      expectedTime: 45,
    },
    // More DBMS
    {
      question: "A schedule is said to be conflict-serializable if:",
      questionType: "single_choice",
      options: [
        "Its precedence graph is acyclic",
        "All transactions are committed",
        "No locks are used",
        "All operations are read-only",
      ],
      correctAnswer: "Its precedence graph is acyclic",
      subjectCode: "DBMS",
      topicName: "Concurrency Control",
      difficulty: "hard",
      marks: 3,
      explanation: "A schedule is conflict-serializable if and only if its precedence (serialization) graph has no cycles.",
      expectedTime: 60,
    },
    {
      question: "Which SQL operation is used in relational algebra's 'projection'?",
      questionType: "single_choice",
      options: ["SELECT specific columns", "SELECT with WHERE", "JOIN", "GROUP BY"],
      correctAnswer: "SELECT specific columns",
      subjectCode: "DBMS",
      topicName: "Relational Algebra",
      difficulty: "easy",
      marks: 2,
      explanation: "Projection in relational algebra selects specific columns (attributes) from a relation, corresponding to listing columns in a SELECT clause.",
      expectedTime: 30,
    },
    // More OS
    {
      question: "Internal fragmentation occurs when:",
      questionType: "single_choice",
      options: [
        "Allocated memory is larger than the requested memory",
        "Free memory exists between allocated blocks",
        "The disk is fragmented",
        "The page table overflows",
      ],
      correctAnswer: "Allocated memory is larger than the requested memory",
      subjectCode: "OS",
      topicName: "Memory Management",
      difficulty: "easy",
      marks: 2,
      explanation: "Internal fragmentation happens when fixed-size allocation gives more memory than needed, wasting space within the allocated block.",
      expectedTime: 30,
    },
    {
      question: "In the producer-consumer problem, the bounded buffer is shared between:",
      questionType: "single_choice",
      options: [
        "Producer and Consumer processes",
        "Two producer processes only",
        "The OS kernel and user processes",
        "CPU and memory controller",
      ],
      correctAnswer: "Producer and Consumer processes",
      subjectCode: "OS",
      topicName: "Process Synchronization",
      difficulty: "easy",
      marks: 2,
      explanation: "The bounded buffer is a shared resource accessed by producer (writes data) and consumer (reads data) processes, requiring synchronization.",
      expectedTime: 30,
    },
    // More CN
    {
      question: "Which protocol is used for secure file transfer?",
      questionType: "single_choice",
      options: ["SFTP", "FTP", "SMTP", "SNMP"],
      correctAnswer: "SFTP",
      subjectCode: "CN",
      topicName: "Network Security",
      difficulty: "easy",
      marks: 2,
      explanation: "SFTP (SSH File Transfer Protocol) provides encrypted file transfer over SSH, unlike plain FTP which sends data in cleartext.",
      expectedTime: 30,
    },
    {
      question: "What is the default port number for HTTPS?",
      questionType: "single_choice",
      options: ["443", "80", "8080", "22"],
      correctAnswer: "443",
      subjectCode: "CN",
      topicName: "HTTP & HTTPS",
      difficulty: "easy",
      marks: 2,
      explanation: "HTTPS uses port 443 by default. HTTP uses port 80.",
      expectedTime: 30,
    },
    // More OOP
    {
      question: "Constructor overloading is an example of:",
      questionType: "single_choice",
      options: ["Compile-time polymorphism", "Runtime polymorphism", "Encapsulation", "Abstraction"],
      correctAnswer: "Compile-time polymorphism",
      subjectCode: "OOP",
      topicName: "Polymorphism",
      difficulty: "easy",
      marks: 2,
      explanation: "Constructor overloading (multiple constructors with different parameters) is resolved at compile time, making it compile-time (static) polymorphism.",
      expectedTime: 30,
    },
    {
      question: "The Factory design pattern is categorized as a:",
      questionType: "single_choice",
      options: ["Creational pattern", "Structural pattern", "Behavioral pattern", "Architectural pattern"],
      correctAnswer: "Creational pattern",
      subjectCode: "OOP",
      topicName: "Design Patterns",
      difficulty: "easy",
      marks: 2,
      explanation: "Factory is a creational pattern — it provides an interface for creating objects without specifying their concrete classes.",
      expectedTime: 30,
    },
    // More SQL
    {
      question: "What does the COALESCE function return?",
      questionType: "single_choice",
      options: [
        "The first non-NULL value in its argument list",
        "The maximum value",
        "The average of all values",
        "The last non-NULL value",
      ],
      correctAnswer: "The first non-NULL value in its argument list",
      subjectCode: "SQL",
      topicName: "SELECT Queries",
      difficulty: "medium",
      marks: 2,
      explanation: "COALESCE evaluates arguments left to right and returns the first non-NULL value.",
      expectedTime: 45,
    },
    {
      question: "A self-join is used when:",
      questionType: "single_choice",
      options: [
        "A table needs to be joined with itself",
        "Two different tables are joined",
        "No join condition exists",
        "Only one column is selected",
      ],
      correctAnswer: "A table needs to be joined with itself",
      subjectCode: "SQL",
      topicName: "Joins",
      difficulty: "medium",
      marks: 2,
      explanation: "A self-join joins a table with itself, typically using aliases, to compare rows within the same table.",
      expectedTime: 45,
    },
    // Additional hard questions
    {
      question: "In the context of OS memory management, what is the primary advantage of paging over segmentation?",
      questionType: "single_choice",
      options: [
        "No external fragmentation",
        "Faster memory access",
        "Simpler implementation",
        "Better security",
      ],
      correctAnswer: "No external fragmentation",
      subjectCode: "OS",
      topicName: "Memory Management",
      difficulty: "medium",
      marks: 2,
      explanation: "Paging divides memory into fixed-size pages, eliminating external fragmentation. It may still have internal fragmentation.",
      expectedTime: 45,
    },
    {
      question: "What is the time complexity of inserting a node into an AVL tree?",
      questionType: "single_choice",
      options: ["O(log n)", "O(n)", "O(1)", "O(n log n)"],
      correctAnswer: "O(log n)",
      subjectCode: "DSA",
      topicName: "Trees",
      difficulty: "medium",
      marks: 2,
      explanation: "AVL trees maintain balance through rotations. Insertion involves traversing to the correct position O(log n) and at most O(1) rotations to rebalance.",
      expectedTime: 45,
    },
    {
      question: "Which of the following is NOT a valid transaction isolation level in SQL?",
      questionType: "single_choice",
      options: ["Read Exclusive", "Read Uncommitted", "Read Committed", "Serializable"],
      correctAnswer: "Read Exclusive",
      subjectCode: "DBMS",
      topicName: "Transactions",
      difficulty: "medium",
      marks: 2,
      explanation: "Standard SQL isolation levels are: Read Uncommitted, Read Committed, Repeatable Read, and Serializable. 'Read Exclusive' is not a standard level.",
      expectedTime: 45,
    },
    {
      question: "Window functions in SQL are executed:",
      questionType: "single_choice",
      options: [
        "After WHERE, GROUP BY, HAVING but before ORDER BY",
        "Before all other clauses",
        "After ORDER BY",
        "Before WHERE",
      ],
      correctAnswer: "After WHERE, GROUP BY, HAVING but before ORDER BY",
      subjectCode: "SQL",
      topicName: "Window Functions",
      difficulty: "hard",
      marks: 3,
      explanation: "Window functions are logically processed after WHERE, GROUP BY, and HAVING, but before the final ORDER BY and LIMIT.",
      expectedTime: 60,
    },
    {
      question: "The Liskov Substitution Principle states that:",
      questionType: "single_choice",
      options: [
        "Objects of a superclass should be replaceable with objects of a subclass without breaking the program",
        "Classes should depend on abstractions, not concrete implementations",
        "Clients should not depend on interfaces they do not use",
        "A class should have only one reason to change",
      ],
      correctAnswer: "Objects of a superclass should be replaceable with objects of a subclass without breaking the program",
      subjectCode: "OOP",
      topicName: "SOLID Principles",
      difficulty: "medium",
      marks: 2,
      explanation: "LSP ensures that a subclass can stand in for its parent class without altering the correctness of the program.",
      expectedTime: 45,
    },
    {
      question: "Which congestion control algorithm does TCP use initially when a connection starts?",
      questionType: "single_choice",
      options: ["Slow Start", "Congestion Avoidance", "Fast Retransmit", "Fast Recovery"],
      correctAnswer: "Slow Start",
      subjectCode: "CN",
      topicName: "Transport Layer",
      difficulty: "medium",
      marks: 2,
      explanation: "TCP begins with Slow Start, exponentially increasing the congestion window until it reaches the slow start threshold, then switches to Congestion Avoidance.",
      expectedTime: 45,
    },
    // Even more to reach 150+
    {
      question: "What is topological sorting used for?",
      questionType: "single_choice",
      options: [
        "Ordering vertices of a DAG such that for every edge (u,v), u comes before v",
        "Sorting an array in O(n) time",
        "Finding strongly connected components",
        "Finding the shortest path",
      ],
      correctAnswer: "Ordering vertices of a DAG such that for every edge (u,v), u comes before v",
      subjectCode: "DSA",
      topicName: "Graphs",
      difficulty: "medium",
      marks: 2,
      explanation: "Topological sort produces a linear ordering of vertices in a Directed Acyclic Graph (DAG) where for every directed edge (u,v), vertex u appears before v.",
      expectedTime: 45,
    },
    {
      question: "Which string matching algorithm uses a hash function to find pattern matches?",
      questionType: "single_choice",
      options: ["Rabin-Karp", "KMP", "Boyer-Moore", "Brute Force"],
      correctAnswer: "Rabin-Karp",
      subjectCode: "DSA",
      topicName: "Strings",
      difficulty: "medium",
      marks: 2,
      explanation: "Rabin-Karp uses rolling hash functions to quickly compare the hash of the pattern with hashes of text substrings.",
      expectedTime: 45,
    },
    {
      question: "If a relation R has attributes {A, B, C, D} and functional dependencies {A→B, B→C, C→D}, then the candidate key is:",
      questionType: "single_choice",
      options: ["{A}", "{A, B}", "{A, B, C}", "{A, D}"],
      correctAnswer: "{A}",
      subjectCode: "DBMS",
      topicName: "Keys",
      difficulty: "medium",
      marks: 2,
      explanation: "A→B→C→D, so A alone determines all other attributes. Therefore {A} is the candidate key.",
      expectedTime: 60,
    },
    {
      question: "The working set model in virtual memory is used to:",
      questionType: "single_choice",
      options: [
        "Determine the minimum number of frames a process needs to avoid thrashing",
        "Calculate total physical memory",
        "Implement FIFO page replacement",
        "Count the number of page faults",
      ],
      correctAnswer: "Determine the minimum number of frames a process needs to avoid thrashing",
      subjectCode: "OS",
      topicName: "Virtual Memory",
      difficulty: "hard",
      marks: 3,
      explanation: "The working set model tracks the set of pages a process is actively using, helping the OS allocate sufficient frames to prevent thrashing.",
      expectedTime: 60,
    },
    {
      question: "In IPv4 subnetting, a /24 subnet mask corresponds to:",
      questionType: "single_choice",
      options: ["255.255.255.0", "255.255.0.0", "255.0.0.0", "255.255.255.128"],
      correctAnswer: "255.255.255.0",
      subjectCode: "CN",
      topicName: "Subnetting",
      difficulty: "easy",
      marks: 2,
      explanation: "/24 means the first 24 bits are 1s: 11111111.11111111.11111111.00000000 = 255.255.255.0.",
      expectedTime: 30,
    },
    {
      question: "The Dependency Inversion Principle states that:",
      questionType: "single_choice",
      options: [
        "High-level modules should not depend on low-level modules; both should depend on abstractions",
        "A class should have only one responsibility",
        "Subclasses should be substitutable for their base classes",
        "Clients should not be forced to depend on interfaces they don't use",
      ],
      correctAnswer: "High-level modules should not depend on low-level modules; both should depend on abstractions",
      subjectCode: "OOP",
      topicName: "SOLID Principles",
      difficulty: "hard",
      marks: 3,
      explanation: "DIP inverts the traditional dependency flow: instead of high-level modules depending on low-level ones, both depend on abstractions.",
      expectedTime: 60,
    },
    {
      question: "What is the output of: SELECT NVL(NULL, 'Default') in Oracle (or COALESCE(NULL, 'Default') in standard SQL)?",
      questionType: "single_choice",
      options: ["Default", "NULL", "Error", "0"],
      correctAnswer: "Default",
      subjectCode: "SQL",
      topicName: "SELECT Queries",
      difficulty: "easy",
      marks: 2,
      explanation: "NVL/COALESCE returns the first non-NULL argument. Since the first is NULL, it returns 'Default'.",
      expectedTime: 30,
    },
    {
      question: "Which type of index would you create on a column that has very few distinct values (low cardinality)?",
      questionType: "single_choice",
      options: ["Bitmap Index", "B-Tree Index", "Hash Index", "Full-Text Index"],
      correctAnswer: "Bitmap Index",
      subjectCode: "DBMS",
      topicName: "Indexing",
      difficulty: "hard",
      marks: 3,
      explanation: "Bitmap indexes are efficient for columns with low cardinality (few distinct values) like gender or status, as they use bit arrays for each distinct value.",
      expectedTime: 60,
    },
    {
      question: "Counting Sort has a time complexity of:",
      questionType: "single_choice",
      options: ["O(n + k)", "O(n log n)", "O(n²)", "O(k log n)"],
      correctAnswer: "O(n + k)",
      subjectCode: "DSA",
      topicName: "Sorting",
      difficulty: "medium",
      marks: 2,
      explanation: "Counting Sort runs in O(n + k) where n is the number of elements and k is the range of input values.",
      expectedTime: 45,
    },
    {
      question: "The Bellman-Ford algorithm can handle:",
      questionType: "single_choice",
      options: ["Negative edge weights", "Only positive weights", "Unweighted graphs only", "Only DAGs"],
      correctAnswer: "Negative edge weights",
      subjectCode: "DSA",
      topicName: "Graphs",
      difficulty: "medium",
      marks: 2,
      explanation: "Unlike Dijkstra's, Bellman-Ford can handle negative edge weights and can detect negative weight cycles.",
      expectedTime: 45,
    },
    {
      question: "In the context of databases, a 'dirty read' occurs when:",
      questionType: "single_choice",
      options: [
        "A transaction reads data modified by an uncommitted transaction",
        "A transaction reads its own modified data",
        "A transaction reads committed data",
        "Two transactions read the same data simultaneously",
      ],
      correctAnswer: "A transaction reads data modified by an uncommitted transaction",
      subjectCode: "DBMS",
      topicName: "Transactions",
      difficulty: "medium",
      marks: 2,
      explanation: "A dirty read occurs when Transaction A reads data that Transaction B has modified but not yet committed. If B rolls back, A has read invalid data.",
      expectedTime: 45,
    },
    {
      question: "What is the purpose of the TRUNCATE command in SQL?",
      questionType: "single_choice",
      options: [
        "Delete all rows from a table without logging individual row deletions",
        "Remove the table structure",
        "Delete specific rows matching a condition",
        "Modify table columns",
      ],
      correctAnswer: "Delete all rows from a table without logging individual row deletions",
      subjectCode: "SQL",
      topicName: "DDL & DML",
      difficulty: "easy",
      marks: 2,
      explanation: "TRUNCATE removes all rows from a table efficiently (DDL operation). Unlike DELETE, it doesn't log individual row deletions and cannot be used with WHERE.",
      expectedTime: 30,
    },
    {
      question: "The number of leaf nodes in a strictly binary tree (full binary tree) with n internal nodes is:",
      questionType: "single_choice",
      options: ["n + 1", "n", "2n", "n - 1"],
      correctAnswer: "n + 1",
      subjectCode: "DSA",
      topicName: "Trees",
      difficulty: "medium",
      marks: 2,
      explanation: "In a strictly binary tree (every internal node has exactly 2 children), the number of leaf nodes = number of internal nodes + 1.",
      expectedTime: 45,
    },
    {
      question: "CIDR notation /28 represents how many host addresses per subnet?",
      questionType: "single_choice",
      options: ["14", "16", "30", "12"],
      correctAnswer: "14",
      subjectCode: "CN",
      topicName: "Subnetting",
      difficulty: "medium",
      marks: 2,
      explanation: "/28 leaves 4 host bits: 2^4 = 16 total addresses - 2 (network + broadcast) = 14 usable host addresses.",
      expectedTime: 60,
    },
    {
      question: "What is method hiding in OOP?",
      questionType: "single_choice",
      options: [
        "A static method in a subclass with the same signature as in the parent class",
        "Making a method private",
        "Deleting a method from a class",
        "Overriding a final method",
      ],
      correctAnswer: "A static method in a subclass with the same signature as in the parent class",
      subjectCode: "OOP",
      topicName: "Inheritance",
      difficulty: "hard",
      marks: 3,
      explanation: "Method hiding occurs when a subclass defines a static method with the same signature as a static method in the parent class. The method called depends on the reference type, not the object type.",
      expectedTime: 60,
    },
    {
      question: "Given tables Employee(id, name, dept_id) and Department(id, name), write the correct join to get employee names with their department names:",
      questionType: "single_choice",
      options: [
        "SELECT e.name, d.name FROM Employee e JOIN Department d ON e.dept_id = d.id",
        "SELECT * FROM Employee, Department",
        "SELECT name FROM Employee JOIN Department",
        "SELECT name FROM Employee WHERE dept_id IN Department",
      ],
      correctAnswer: "SELECT e.name, d.name FROM Employee e JOIN Department d ON e.dept_id = d.id",
      subjectCode: "SQL",
      topicName: "Joins",
      difficulty: "easy",
      marks: 2,
      explanation: "This uses an INNER JOIN with proper aliases and an ON clause matching Employee.dept_id with Department.id.",
      expectedTime: 30,
    },
    {
      question: "Which type of DNS record maps a domain name to an IPv4 address?",
      questionType: "single_choice",
      options: ["A record", "CNAME record", "MX record", "AAAA record"],
      correctAnswer: "A record",
      subjectCode: "CN",
      topicName: "DNS",
      difficulty: "easy",
      marks: 2,
      explanation: "An A (Address) record maps a domain name to an IPv4 address. AAAA maps to IPv6.",
      expectedTime: 30,
    },
    {
      question: "What advantage does a B+ tree have over a B tree for database indexing?",
      questionType: "single_choice",
      options: [
        "All data pointers are in leaf nodes, allowing efficient range queries via linked leaves",
        "B+ trees use less disk space",
        "B+ trees are always shorter",
        "B+ trees don't need balancing",
      ],
      correctAnswer: "All data pointers are in leaf nodes, allowing efficient range queries via linked leaves",
      subjectCode: "DBMS",
      topicName: "Indexing",
      difficulty: "hard",
      marks: 3,
      explanation: "In a B+ tree, all data resides in leaf nodes which are linked together, making sequential access and range queries very efficient.",
      expectedTime: 60,
    },
    {
      question: "What is the purpose of the 'volatile' keyword in Java/C++?",
      questionType: "single_choice",
      options: [
        "It tells the compiler that the variable may be changed by external factors and should not be cached",
        "It makes the variable constant",
        "It allocates memory on the heap",
        "It makes the variable thread-safe",
      ],
      correctAnswer: "It tells the compiler that the variable may be changed by external factors and should not be cached",
      subjectCode: "OOP",
      topicName: "Classes & Objects",
      difficulty: "hard",
      marks: 3,
      explanation: "The volatile keyword prevents compiler optimizations that cache the variable, ensuring reads always fetch the latest value from memory.",
      expectedTime: 60,
    },
    {
      question: "ROW_NUMBER() vs RANK() vs DENSE_RANK(): which one always assigns unique sequential integers?",
      questionType: "single_choice",
      options: ["ROW_NUMBER()", "RANK()", "DENSE_RANK()", "All of them"],
      correctAnswer: "ROW_NUMBER()",
      subjectCode: "SQL",
      topicName: "Window Functions",
      difficulty: "medium",
      marks: 2,
      explanation: "ROW_NUMBER() always assigns unique sequential integers (1,2,3,...) regardless of ties. RANK() and DENSE_RANK() assign the same value to tied rows.",
      expectedTime: 45,
    },
    {
      question: "Which of the following is an example of compile-time polymorphism?",
      questionType: "single_choice",
      options: ["Method overloading", "Method overriding", "Virtual functions", "Dynamic dispatch"],
      correctAnswer: "Method overloading",
      subjectCode: "OOP",
      topicName: "Polymorphism",
      difficulty: "easy",
      marks: 2,
      explanation: "Method overloading (same name, different parameters) is resolved at compile time. Method overriding is resolved at runtime.",
      expectedTime: 30,
    },
    {
      question: "In the context of OS, what is a context switch?",
      questionType: "single_choice",
      options: [
        "Saving and restoring the state of a CPU so that execution can resume later",
        "Switching between user mode and kernel mode",
        "Changing the file system",
        "Rebooting the computer",
      ],
      correctAnswer: "Saving and restoring the state of a CPU so that execution can resume later",
      subjectCode: "OS",
      topicName: "Processes",
      difficulty: "easy",
      marks: 2,
      explanation: "A context switch saves the current process's state (registers, PC, etc.) and loads the saved state of another process to resume its execution.",
      expectedTime: 30,
    },
    {
      question: "What is the primary purpose of the Address Resolution Protocol (ARP)?",
      questionType: "single_choice",
      options: [
        "Map IP addresses to MAC addresses on a local network",
        "Assign IP addresses automatically",
        "Route packets across networks",
        "Encrypt network traffic",
      ],
      correctAnswer: "Map IP addresses to MAC addresses on a local network",
      subjectCode: "CN",
      topicName: "TCP/IP",
      difficulty: "easy",
      marks: 2,
      explanation: "ARP translates a 32-bit IP address to a 48-bit MAC address, enabling communication at the data link layer within a LAN.",
      expectedTime: 30,
    },
    {
      question: "Which data structure is most appropriate for implementing an undo feature?",
      questionType: "single_choice",
      options: ["Stack", "Queue", "Linked List", "Hash Table"],
      correctAnswer: "Stack",
      subjectCode: "DSA",
      topicName: "Stacks",
      difficulty: "easy",
      marks: 2,
      explanation: "A stack follows LIFO (Last In, First Out) order, which naturally supports undo operations — the most recent action is undone first.",
      expectedTime: 30,
    },
    {
      question: "What is a deadlock in an operating system?",
      questionType: "single_choice",
      options: [
        "A situation where two or more processes are unable to proceed because each is waiting for a resource held by another",
        "A process that runs indefinitely",
        "A memory leak",
        "A CPU scheduling error",
      ],
      correctAnswer: "A situation where two or more processes are unable to proceed because each is waiting for a resource held by another",
      subjectCode: "OS",
      topicName: "Deadlocks",
      difficulty: "easy",
      marks: 2,
      explanation: "Deadlock is a state where processes are blocked because each one holds resources that another needs, creating a circular wait.",
      expectedTime: 30,
    },
    {
      question: "In SQL, the UNION operator differs from UNION ALL in that:",
      questionType: "single_choice",
      options: [
        "UNION removes duplicates; UNION ALL does not",
        "UNION ALL is faster and also removes duplicates",
        "UNION cannot combine more than two tables",
        "UNION ALL requires matching column names",
      ],
      correctAnswer: "UNION removes duplicates; UNION ALL does not",
      subjectCode: "SQL",
      topicName: "SELECT Queries",
      difficulty: "easy",
      marks: 2,
      explanation: "UNION combines result sets and removes duplicate rows. UNION ALL combines result sets without removing duplicates, making it faster.",
      expectedTime: 30,
    },
  ];

  // Insert all questions
  const insertedQuestions = await db
    .insert(questions)
    .values(
      allQuestions.map((q) => ({
        question: q.question,
        questionType: q.questionType,
        options: q.options,
        correctAnswer: q.correctAnswer,
        subjectId: subjectMap[q.subjectCode],
        topicId: topicMap[`${q.subjectCode}:${q.topicName}`],
        difficulty: q.difficulty,
        marks: q.marks,
        explanation: q.explanation,
        expectedTime: q.expectedTime,
      }))
    )
    .returning();

  console.log(`  ✓ ${insertedQuestions.length} questions created`);

  // ==========================================
  // 4. TESTS
  // ==========================================
  console.log("📝 Creating tests...");

  // Get questions by subject for test assignment
  const questionsBySubject: Record<string, typeof insertedQuestions> = {};
  insertedQuestions.forEach((q, i) => {
    const code = allQuestions[i].subjectCode;
    if (!questionsBySubject[code]) questionsBySubject[code] = [];
    questionsBySubject[code].push(q);
  });

  // Baseline Assessment — mix of all subjects
  const baselineTest = await db
    .insert(tests)
    .values({
      title: "Baseline Assessment",
      description:
        "Comprehensive assessment to establish your initial placement readiness across all core subjects. This measures your starting skill profile in aptitude and computer science fundamentals.",
      type: "baseline",
      duration: 90,
      difficulty: "medium",
      totalMarks: 100,
      isPublished: true,
    })
    .returning();

  // Aptitude Test
  const aptitudeTest = await db
    .insert(tests)
    .values({
      title: "Aptitude Assessment",
      description:
        "Quantitative aptitude, logical reasoning, and verbal ability. Tests your problem-solving speed and analytical thinking under timed conditions.",
      type: "aptitude",
      duration: 60,
      difficulty: "medium",
      totalMarks: 100,
      isPublished: true,
    })
    .returning();

  // CS Fundamentals Test
  const csTest = await db
    .insert(tests)
    .values({
      title: "CS Fundamentals",
      description:
        "Operating Systems, DBMS, Computer Networks, and Core Data Structures. Evaluates your depth of understanding in computer science theory.",
      type: "cs_fundamentals",
      duration: 90,
      difficulty: "hard",
      totalMarks: 100,
      isPublished: true,
    })
    .returning();

  // Mixed Placement Test
  const mixedTest = await db
    .insert(tests)
    .values({
      title: "Mixed Placement Test",
      description:
        "A comprehensive simulation designed to evaluate your readiness across multiple domains. This test mirrors the standard pattern of top-tier technology companies.",
      type: "mixed",
      duration: 120,
      difficulty: "medium",
      totalMarks: 100,
      isPublished: true,
    })
    .returning();

  console.log("  ✓ 4 tests created");

  // ==========================================
  // 5. TEST-QUESTION ASSIGNMENTS
  // ==========================================
  console.log("🔗 Linking questions to tests...");

  // Helper to pick N questions from subjects
  function pickQuestions(
    subjectCodes: string[],
    count: number
  ): typeof insertedQuestions {
    const pool: typeof insertedQuestions = [];
    subjectCodes.forEach((code) => {
      if (questionsBySubject[code]) {
        pool.push(...questionsBySubject[code]);
      }
    });
    // Shuffle and pick
    const shuffled = pool.sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  }

  // Baseline: 50 questions across all subjects
  const baselineQuestions = pickQuestions(
    ["APT", "DSA", "DBMS", "OS", "CN", "OOP", "SQL"],
    50
  );
  await db.insert(testQuestions).values(
    baselineQuestions.map((q, i) => ({
      testId: baselineTest[0].id,
      questionId: q.id,
      questionOrder: i + 1,
    }))
  );

  // Aptitude: all aptitude questions
  const aptQuestions = questionsBySubject["APT"] || [];
  await db.insert(testQuestions).values(
    aptQuestions.map((q, i) => ({
      testId: aptitudeTest[0].id,
      questionId: q.id,
      questionOrder: i + 1,
    }))
  );

  // CS Fundamentals: DSA + DBMS + OS + CN + OOP questions
  const csQuestions = pickQuestions(
    ["DSA", "DBMS", "OS", "CN", "OOP"],
    50
  );
  await db.insert(testQuestions).values(
    csQuestions.map((q, i) => ({
      testId: csTest[0].id,
      questionId: q.id,
      questionOrder: i + 1,
    }))
  );

  // Mixed: mix of everything
  const mixedQuestions = pickQuestions(
    ["APT", "DSA", "DBMS", "OS", "CN", "OOP", "SQL"],
    60
  );
  await db.insert(testQuestions).values(
    mixedQuestions.map((q, i) => ({
      testId: mixedTest[0].id,
      questionId: q.id,
      questionOrder: i + 1,
    }))
  );

  console.log("  ✓ Test-question links created");

  // ==========================================
  // 6. ADMIN USER (optional demo user)
  // ==========================================
  console.log("👤 Creating admin user...");
  const adminPasswordHash = await bcrypt.hash("admin123", 12);
  const adminUser = await db
    .insert(users)
    .values({
      email: "admin@placementos.dev",
      passwordHash: adminPasswordHash,
      isAdmin: true,
    })
    .returning();

  await db.insert(profiles).values({
    userId: adminUser[0].id,
    name: "Admin",
    college: "Placement OS",
    branch: "Platform Engineering",
    graduationYear: 2025,
    preferredLanguage: "TypeScript",
  });

  console.log("  ✓ Admin user created (admin@placementos.dev / admin123)");

  // ==========================================
  // DONE
  // ==========================================
  console.log("\n✅ Seeding complete!");
  console.log(`   ${insertedSubjects.length} subjects`);
  console.log(`   ${insertedTopics.length} topics`);
  console.log(`   ${insertedQuestions.length} questions`);
  console.log(`   4 tests`);
  console.log(`   1 admin user`);

  await pool.end();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
